version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: solanki-lab-mcp-gateway_mcp-gateway_1
      APP_PORT: 3333

  mcp-gateway:
    image: ghcr.io/weirdlywild/mcp-gateway:0.7.1@sha256:0b7ae27720dc0794efbd277a44dfffb9f1807dce2bbbcfca238e8a6b7d0a3b63
    restart: on-failure
    init: true
    environment:
      MCP_GATEWAY_PORT: "3333"
      MCP_GATEWAY_STORAGE: /data
      MCP_GATEWAY_TOKEN: ${APP_PASSWORD}
      DEBUG: ""
    volumes:
      - ${APP_DATA_DIR}/data:/data
