FROM ghcr.io/browserless/chromium:v2.56.7@sha256:b1ba7b054af2891a8199f884d4bd249cf8c3bd2fa8a97b339077e40f92803ba8

COPY external/browser.js /usr/src/app/external/browser.js
COPY external/page.js /usr/src/app/external/page.js

USER blessuser
